export const FETCH_BALANCE = 'FETCH_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';
export const ADD_CREDITS = 'ADD_CREDITS';
export const WITHDRAW_CREDITS = 'WITHDRAW_CREDITS';
export const INCREASE_EQUITY = 'INCREASE_EQUITY';
export const DECREASE_EQUITY = 'DECREASE_EQUITY';

export const FETCH_SHARES = 'FETCH_SHARES';
export const RECEIVE_SHARES = 'RECEIVE_SHARES';
export const RECEIVE_SINGLE_SHARE = 'RECEIVE_SINGLE_SHARE';
export const SEARCH_SHARE = 'SEARCH_SHARE';
export const FETCH_SHARE_BY_SYMBOL = 'FETCH_SHARE_BY_SYMBOL';

export const BUY_SHARES = 'BUY_SHARES';
export const SELL_SHARES = 'SELL_SHARES';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';

export const REAL_API_RECEIVE_SINGLE_SHARE = 'REAL_API_RECEIVE_SINGLE_SHARE';
export const REAL_API_REQUEST_SINGLE_SHARE = 'REAL_API_REQUEST_SINGLE_SHARE';
